CompanyWebApp/blog_posts/forms.py
#blog_posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class BlogPostForm(FlaskForm):
    title = StringField('标题', validators=[DataRequired()])
    text = TextAreaField('博客内容', validators=[DataRequired()])
    submit = SubmitField('提交')

CompanyWebApp/blog_posts/views.py
#blog_posts/VIEW.PY
from flask import render_template, url_for, flash, request, redirect, Blueprint, abort
from flask_login import current_user, login_required
from CompanyWebApp import db
from CompanyWebApp.models import BlogPost
from CompanyWebApp.blog_posts.forms import BlogPostForm

blog_posts = Blueprint('blog_posts',__name__)

#CREATE POST
@blog_posts.route('/create', methods=['GET','POST'])
@login_required
def create_post():
    form = BlogPostForm()

    if form.validate_on_submit():

        blog_post = BlogPost(title=form.title.data, text=form.text.data, user_id=current_user.id)
        db.session.add(blog_post)
        db.session.commit()
        flash('创建了一条博文！')

        return redirect(url_for('core.index'))
    
    return render_template('create_post.html', form=form)

#BLOG POST(view)
@blog_posts.route('/<int:blog_post_id>') 
def blog_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    return render_template('blog_post.html', title=blog_post.title, date=blog_post.date, post=blog_post)

#UPDATE POST
@blog_posts.route('/<int:blog_post_id>/update', methods=['GET', 'POST'])  
@login_required
def update(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)

    if blog_post.author != current_user:
        abort(403)

    form = BlogPostForm()

    if form.validate_on_submit():

        blog_post.title = form.title.data 
        blog_post.text = form.text.data
        db.session.commit()
        flash('更新了一条博文！')

        return redirect(url_for('blog_posts.blog_post', blog_post_id = blog_post_id))

    elif request.method == 'GET':
        form.title.data = blog_post.title
        form.text.data = blog_post.text 

    return render_template('create_post.html', title='Updating', form = form)
 
#DELETE POST
@blog_posts.route('/<int:blog_post_id>/delete', methods=['GET', 'POST'])  
@login_required
def delete_post(blog_post_id):

    blog_post = BlogPost.query.get_or_404(blog_post_id)

    if blog_post.author != current_user:
        abort(403)

    db.session.delete(blog_post)
    db.session.commit()
    flash('删除了一条博文')
    return redirect(url_for('core.index'))

CompanyWebApp/core/views.py
#core/views.py
from flask import render_template, request, Blueprint
from CompanyWebApp.models import BlogPost

core = Blueprint('core', __name__)

#homepage
@core.route('/')
def index():
    page = request.args.get('page',1,type=int)

    blog_posts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page, per_page=5)

    return render_template('index.html', blog_posts=blog_posts)

#infopage
@core.route('/info')
def info():
    return render_template('info.html')

CompanyWebApp/irr_calculators/views.py
#IRR_CALCULATOR/views.py
from flask import render_template,url_for,flash,redirect,request,Blueprint,session
from flask_login import current_user, login_required
from CompanyWebApp import db
from CompanyWebApp.models import Trade, CashFlow
from CompanyWebApp.irr_calculators.forms import TradeForm, CashflowForm, LeaseDateForm
from datetime import datetime, date
from CompanyWebApp.irr_calculators.cashflow_generate import add_cashflows, xirr, eirr

irr_calculators = Blueprint('irr_calculators', __name__)

#TRADE LIST
@irr_calculators.route('/trade_list', methods = ['GET','POST'])
@login_required
def trade_list():

    trans = Trade.query.order_by(Trade.id.desc())

    return render_template('irr_trade_list.html', trans = trans)

#CREATE A TRADE
@irr_calculators.route('/trade_create', methods=['GET', 'POST'])
@login_required
def trade_create():

    form = TradeForm()

    if form.validate_on_submit():

        new_trade = Trade(equip_amount=form.equip_amount.data, rent_period=form.rent_period.data, downpayment=form.downpayment.data, deposit=form.deposit.data,fee=form.fee.data, flat_rate=form.flat_rate.data,payment_type=form.payment_type.data,payment_period=form.payment_period.data,irr_nor=0,irr_exp=0)
        db.session.add(new_trade)
        db.session.commit()

        flash('您已经成功添加一项交易！')
        
        return redirect(url_for('irr_calculators.trade_list'))
    return render_template('irr_trade_create.html', form=form)

#UPDATE A TRADE
@irr_calculators.route('/<int:trade_id>/trade_update', methods = ['GET','POST'])
@login_required
def trade_update(trade_id):
    
    trade = Trade.query.get_or_404(trade_id)
    
    form = TradeForm()

    if form.validate_on_submit():
        trade.equip_amount = form.equip_amount.data
        trade.rent_period = form.rent_period.data
        trade.downpayment = form.downpayment.data
        trade.deposit = form.deposit.data
        trade.fee = form.fee.data
        trade.flat_rate= form.flat_rate.data
        trade.payment_type = form.payment_type.data
        trade.payment_period = form.payment_period.data
        db.session.commit()
        
        # cashflows = CashFlow.query.filter_by(tra_id=trade.id)
        # # update default cashflows to the cashflow database
        # # equip_amount_payment
        # cashflow_equip_payment = CashFlow(trade.id,datetime.utcnow(),"设备款项", "流入",trade.equip_amount, trade.equip_amount/1.13*0.13)
        # # down_payment
        # cashflow_down_payment = CashFlow(trade.id,datetime.utcnow(),"首付款", "流出",-trade.downpayment, -trade.downpayment/1.13*0.13)
        # # deposit
        # cashflow_deposit = CashFlow(trade.id,datetime.utcnow(),"保证金", "流出",-trade.deposit, -trade.deposit/1.13*0.13)
        # # fee
        # cashflow_fee = CashFlow(trade.id,datetime.utcnow(),"费用", "流出",-trade.fee, -trade.fee/1.13*0.13)
        # db.session.add_all([cashflow_equip_payment,cashflow_down_payment,cashflow_deposit,cashflow_fee])
        # db.session.commit()  
        
        flash(f'更新了{trade.id}号交易！')

        return redirect(url_for('irr_calculators.trade_list'))
    
    elif request.method == 'GET':
        form.equip_amount.data = trade.equip_amount
        form.rent_period.data = trade.rent_period
        form.downpayment.data = trade.downpayment 
        form.deposit.data = trade.deposit
        form.fee.data = trade.fee 
        form.flat_rate.data = trade.flat_rate 
        form.payment_type.data = trade.payment_type 
        form.payment_period.data = trade.payment_period

    return render_template('irr_trade_create.html', form=form, trade=trade)

#DELETE A TRADE
@irr_calculators.route('/<int:trade_id>/trade_delete', methods = ['GET','POST'])
@login_required
def trade_delete(trade_id):
    trade = Trade.query.get_or_404(trade_id)

    db.session.delete(trade)
    db.session.commit()
    flash(f'删除了{trade.id}号交易')
    return redirect(url_for('irr_calculators.trade_list'))

#Cashflows and IRR
@irr_calculators.route('/<trade_id>/irr_cashflows', methods = ['GET','POST'])
@login_required
def irr_cashflows(trade_id):
    trade = Trade.query.filter_by(id=trade_id).first()
    XIRR = trade.irr_nor
    EIRR = trade.irr_exp
    equip_amount = trade.equip_amount
    rent_period = trade.rent_period
    downpayment = trade.downpayment
    deposit = trade.deposit
    fee = trade.fee
    payment_period = trade.payment_period
    cashflows = CashFlow.query.filter_by(tra_id=trade_id).order_by(CashFlow.date.asc())
    form = LeaseDateForm()
    count = 0
    if form.validate_on_submit():
        lease_date = form.lease_date.data
        period_end_or_beg = form.period_end_or_beg.data
        basic_rent = form.basic_rent.data

        for cashflow in cashflows:
            db.session.delete(cashflow)
        add_cashflows(trade_id, equip_amount, rent_period,downpayment, deposit, fee,payment_period,lease_date,period_end_or_beg, basic_rent)
        return redirect(url_for('irr_calculators.irr_cashflows', trade_id=trade_id))

    return render_template('irr_cashflows.html', trade_id=trade_id, cashflows = cashflows, trade=trade, form=form, count=count, XIRR=XIRR, EIRR=EIRR)

#CREATE A CASHFLOW
@irr_calculators.route('/<trade_id>/cashflow_create', methods=['GET', 'POST'])
@login_required
def cashflow_create(trade_id):

    form = CashflowForm()

    if form.validate_on_submit():

        new_cashflow = CashFlow(tra_id=trade_id, date=form.date.data, cashflow_nature=form.cashflow_nature.data, cashflow_type=form.cashflow_type.data,cashflow_amount=form.cashflow_amount.data, cashflow_tax=form.cashflow_tax.data)
        db.session.add(new_cashflow)
        db.session.commit()
        flash('您已经成功添加一条现金流！')
        return redirect(url_for('irr_calculators.irr_cashflows', trade_id=trade_id))
    return render_template('irr_cashflow_create.html', form=form, trade_id=trade_id)

#DELETE A CASHFLOW
@irr_calculators.route('/<int:cashflow_id>/cashflow_delete', methods = ['GET','POST'])
@login_required
def cashflow_delete(cashflow_id):
    cashflow = CashFlow.query.get_or_404(cashflow_id)
    trade_id = cashflow.tra_id
    db.session.delete(cashflow)
    db.session.commit()
    flash('删除了一条现金流')
    return redirect(url_for('irr_calculators.irr_cashflows', trade_id=trade_id))

#UPDATE A CASHFLOW
@irr_calculators.route('/<int:cashflow_id>/cashflow_update', methods = ['GET','POST'])
@login_required
def cashflow_update(cashflow_id):
    
    cashflow = CashFlow.query.get_or_404(cashflow_id)
    trade_id = cashflow.tra_id
    form = CashflowForm()

    if form.validate_on_submit():
        cashflow.date = form.date.data
        cashflow.cashflow_nature = form.cashflow_nature.data
        cashflow.cashflow_type = form.cashflow_type.data
        cashflow.cashflow_amount = form.cashflow_amount.data
        cashflow.cashflow_tax = form.cashflow_tax.data
        db.session.commit()
        
        flash(f'更新了一条现金流！')

        return redirect(url_for('irr_calculators.irr_cashflows', trade_id=trade_id))
    
    elif request.method == 'GET':
        form.date.data = cashflow.date 
        form.cashflow_nature.data = cashflow.cashflow_nature 
        form.cashflow_type.data = cashflow.cashflow_type 
        form.cashflow_amount.data = cashflow.cashflow_amount  
        form.cashflow_tax.data = cashflow.cashflow_tax 

    return render_template('irr_cashflow_create.html', form= form)

#calculate xirr and eirr
@irr_calculators.route('/<int:trade_id>/calculate_irr', methods = ['GET','POST'])
@login_required
def calculate_irr(trade_id):
    cashflows=CashFlow.query.filter_by(tra_id=trade_id).order_by(CashFlow.date.asc())
    cashflow_data=[]
    for cashflow in cashflows:
        time = cashflow.date
        amount = cashflow.cashflow_amount
        cashflow_data.append((time,amount))
    XIRR = xirr(cashflow_data)
    EIRR = eirr(cashflow_data)
    trade = Trade.query.filter_by(id=trade_id).first()

    try:
        trade.irr_nor = round(float(XIRR*100),4)
        trade.irr_exp = round(float(EIRR*100),4)
    except:
        trade.irr_nor = 0
        trade.irr_exp = 0
    db.session.commit()
    flash(f'IRR已经重新计算！XIRR:{trade.irr_nor}%/年, 连续复利IRR{trade.irr_exp}%/年')
    return redirect(url_for('irr_calculators.irr_cashflows', trade_id=trade_id))
    

CompanyWebApp/users/views.py
#users/views.py
from flask import render_template,url_for,flash,redirect,request,Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from CompanyWebApp import db
from CompanyWebApp.models import User, BlogPost
from CompanyWebApp.users.forms import  RegistrationForm, LoginForm, UpdateUserForm
from CompanyWebApp.users.picture_handler import add_profile_pic
  
users = Blueprint('users', __name__)
 
#REGISTRATION
@users.route('/register', methods=['POST','GET'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(email=form.email.data,username=form.username.data,user_dep='外部', user_level='普通用户', admin=False, password=form.password.data, )

        db.session.add(user)
        db.session.commit()
        flash('感谢注册!')
        return redirect(url_for('users.login'))
    
    return render_template('user_register.html', form=form)

#LOGIN
@users.route('/login', methods=['POST','GET'])
def login():
    
    form = LoginForm()
    
    if form.validate_on_submit():

        user = User.query.filter_by(email=form.email.data).first()
        
        if  user is not None and user.check_password(form.password.data):
            login_user(user)
            flash('登录成功!')
            #IMPORTANT NEXT
            next = request.args.get('next')
            if next == None or not next[0] == '/':
                next = url_for('core.index')
            return redirect(next)

    return render_template('user_login.html', form = form)

#LOGOUT
@users.route('/logout')
def logout():
    logout_user()
    flash('用户已登出!')
    return redirect(url_for('core.index'))

#ACCOUNT (update UserForm) //// maybe need to change to account/<user_id>
@users.route('/account', methods=['GET','POST'])
@login_required
def account():

    form = UpdateUserForm()
    if form.validate_on_submit():
        if form.picture.data:
            # GRAB THE NEW IMAGE TO UPDATE profile_image
            username = current_user.username
            pic = add_profile_pic(form.picture.data, username)
            current_user.profile_image = pic
        
        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.user_dep = form.department.data
        current_user.user_level = form.level.data
        current_user.admin = form.admin.data

        db.session.commit()
        flash('用户信息成功更新!')

        return redirect(url_for('users.account'))

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.department.data = current_user.user_dep
        form.level.data = current_user.user_level
        form.admin.data = current_user.admin
    
    profile_image = url_for('static', filename= 'profile_pics/'+current_user.profile_image)

    return render_template('user_account.html', profile_image= profile_image, form=form)

#USER POST LIST VIEW
@users.route('/<username>')
def user_posts(username):
    page = request.args.get('page',1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    blog_posts = BlogPost.query.filter_by(author=user).order_by(BlogPost.date.desc()).paginate(page=page, per_page=5)

    return render_template('user_blog_posts.html', blog_posts = blog_posts, user= user )

CompanyWebApp/templates/basic.html
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title> 
  </head>
  <body>
  <ul class="nav">
    <li class="navbar-brand" href="#">
      <img src="../static/companylogo.png" width="85" height="30" alt="" loading="lazy">
    </li>
    <li class="nav-item">
    <a class="nav-link" href="{{ url_for('core.index') }}">首页</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{{ url_for('core.info') }}">关于</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{{ url_for('blog_posts.create_post')}}">发表博客</a>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        功能
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="{{ url_for('irr_calculators.trade_list')}}">IRR测算</a>
      </div>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        账户管理
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        {% if current_user.is_authenticated %}
        <a class="dropdown-item" href="{{ url_for('users.logout') }}">登出</a>
        {% else %}
        <a class="dropdown-item" href="{{ url_for('users.register') }}">注册</a>        
        <a class="dropdown-item" href="{{ url_for('users.login') }}">登录</a>
        {% endif %}
        {% if current_user.is_authenticated %}
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="{{ url_for('users.account') }}">用户管理</a>
        {% endif %}
      </div>
    </li>
    {% if current_user.is_authenticated %}
    <div class="">
      <span class="navbar-text">
       <strong>{{current_user.username}}</strong>, 欢迎您登入！
      </span>
    </div>
    {% endif %}

</ul>
<div class="container">
  {% block content %}

  {% endblock %}
</div>
<br>
<div align='center'>
  <strong>CopyRight©2020 贵安恒信</strong> 
</div>
<br>
<br>
<br>
<br>
<br>
<br>


  </body>
</html>

CompanyWebApp/templates/create_post.html
{% extends "basic.html" %}
{% block title %}
创建博文
{% endblock %}
{% block content %}
{% for mess in get_flashed_messages() %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <button type="button" class=" fade close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  <strong>{{ mess }}</strong> 
</div>
{% endfor %}
    <div class="container">
        <form action="" class="form-group" method="POST">
            {{form.hidden_tag()}}

            <div class="form-group">
                {{form.title.label(class="form-control-label")}}
                {{form.title(class="form-control form-control-lg")}}                
            </div>
            <div class="form-group">
                {{form.text.label(class="form-control-label")}}
                {{form.text(class="form-control form-control-lg")}}                
            </div>
            <div class="form-group">
                {{form.submit(class="btn btn-outline-info")}}
            </div>

        </form>
    </div>

{% endblock %}

CompanyWebApp/templates/info.html
{% extends "basic.html" %}
{% block title %}
介绍
{% endblock %}
{% block content %}
<div class="jumbotron">
    <h2>在这里您可以发表博客，并尝试我们为您准备的各种金融功能模块</h2>
    <br>
    <h5>金融功能模块介绍：</h5>
    <ul>
        <li>功能/IRR测算：您可以登记一笔潜在交易，修改或管理它的各项交易要素与租金计划，并测算相应实际资金成本（普通IRR与连续复利IRR）。</li>
    </ul>
    <br>
    <h5>别忘了注册账号哦！</h5>
    
</div>
{% endblock %}

CompanyWebApp/templates/irr_cashflows.html
{% extends "basic.html" %}
{% block title %}
IRR测算
{% endblock %}
{% block content %}
{% for mess in get_flashed_messages() %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <button type="button" class=" fade close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  <strong>{{ mess }}</strong> 
</div>
{% endfor %}
   
    <div class="jumbotron">
      <h3> {{trade_id}} 号交易 </h3>
      <br>
      <div class="row">
        <div class="col-md-3">
          <h5><strong>设备金额:</strong></h5>
        </div>
        <div class="col-md-3">
          <h5>{{trade.equip_amount}} 元 </h5>
        </div>
        <div class="col-md-3">
          <h5><strong>首付款:</strong></h5>
        </div>
        <div class="col-md-3">
          <h5>{{trade.downpayment}} 元 </h5>
        </div>
      </div>
      <div class="row">
        <div class="col-md-3">
          <h5><strong>保证金:</strong> </h5>
        </div>
        <div class="col-md-3">
          <h5>{{trade.deposit}} 元 </h5>
        </div>
        <div class="col-md-3">
          <h5><strong>费用: </strong></h5>
        </div>
        <div class="col-md-3">
          <h5>{{trade.fee}} 元 </h5>
        </div>
      </div>
      <div class="row">
        <div class="col-md-3">
          <h5><strong>租金期数: </strong></h5>
        </div>
        <div class="col-md-3">
          <h5>{{trade.rent_period}} 期 </h5>
        </div>
        <div class="col-md-3">
          <h5><strong>付款方式:</strong></h5>
        </div>
        <div class="col-md-3">
          <h5>{{trade.payment_type}}  </h5>
        </div>
      </div>
      <div class="row">
        <div class="col-md-3">
          <h5><strong>付款间隙: </strong></h5>
        </div>
        <div class="col-md-3">
          <h5>{{trade.payment_period}}  </h5>
        </div>
        <div class="col-md-3">
          <h5><strong>平面利息: </strong></h5>
        </div>
        <div class="col-md-3">
          <h5>{{trade.flat_rate*100}}%/年</h5>
        </div>
      </div>
      <br>
      <p>请确认起租日与租金支付时间，来更新现金流计划</p>
      <form method="POST">
        {{ form.hidden_tag() }}
        <div class="form-row">
          <div class="form-group col-md-4">
            {{form.lease_date.label}}
            {{form.lease_date(class="form-control", placeholder="")}}
          </div>
          <div class="form-group col-md-4">
            {{form.period_end_or_beg.label}}
            {{form.period_end_or_beg(class="form-control", placeholder="")}}
          </div>
          <div class="form-group col-md-4">
            {{form.basic_rent.label}}
            {{form.basic_rent(class="form-control", placeholder="")}}
          </div>
        </div>
        {{ form.submit(class="btn btn-primary btn-sm")}}
      </form>
      <br>
        <h3> 详细现金流计划如下： </h3>
        <p>点击更新/删除来调整单项现金流</p>
        <p>添加现金流</p>
        <a href="{{ url_for('irr_calculators.cashflow_create', trade_id=trade_id)}}"><button type="button" class="btn btn-primary btn-sm">添加现金流</button></a>
        <br>
        <br>
        <table class="table table-striped">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">日期</th>
                <th scope="col">款项性质</th>
                <th scope="col">金额</th>
                <th scope="col">流入/出</th>
                <th scope="col">税额</th>
                <th scope="col">不含税金额</th>
              </tr>
            </thead>
            <tbody>
              {% for cashflow in cashflows %}
              <tr>
                <th scope="row">{{ loop.index }}</th>
                <td>{{ cashflow.date }}</td>
                <td>{{ cashflow.cashflow_nature }}</td>
                <td>{{ cashflow.cashflow_amount }}</td>
                <td>{{ cashflow.cashflow_type }}</td>
                <td>{{ cashflow.cashflow_tax }}</td>
                <td>{{ cashflow.cashflow_amount-cashflow.cashflow_tax }}</td>
                <td><a href="{{ url_for('irr_calculators.cashflow_update', cashflow_id=cashflow.id )}}"> <button type="button" class="btn btn-primary btn-sm">更新</button></a></td>
                <td><a href="{{ url_for('irr_calculators.cashflow_delete', cashflow_id=cashflow.id )}}"> <button type="button" class="btn btn-danger btn-sm">删除</button></a></td>
              </tr>
              {% endfor %}
              
            </tbody>
          </table>
          <br>
          <form action="{{url_for('irr_calculators.calculate_irr', trade_id=trade_id)}}" method="POST">
            <button type="submit" class="btn btn-primary" >测算资金成本</button>
          </form>
          
          <br>
          <table class="table table-borderless">

            <tbody>
              <tr>
                <th scope="row"> {{trade.id}} 号交易的XIRR为：</th>
                <td><strong>{{ XIRR }}%/年</strong></td>
              </tr>
              <tr>
                <th scope="row"> {{trade_id}} 号交易的连续复利IRR为：</th>
                <td><strong>{{ EIRR }}%/年</strong></td>
              </tr>
            </tbody>
          </table>
    </div>


{% endblock %}

CompanyWebApp/templates/irr_trade_list.html
{% extends "basic.html" %}
{% block title %}
交易汇总
{% endblock %}

{% block content %}
{% for mess in get_flashed_messages() %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <button type="button" class=" fade close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  <strong>{{ mess }}</strong> 
</div>
{% endfor %}
<br>
<h3>请建立一笔交易来测算资金成本，您也可以通过浏览过往交易来更新IRR测算</h3>
<br>
<a href="{{ url_for('irr_calculators.trade_create')}}"><button type="button" class="btn btn-primary" >创建新交易</button></a>
<br>
<div>
    <br>
    <h3>历史交易明细如下：</h3>
    <br>
</div>
<div class="jumbotron">
  <div class="table-responsive-md">
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">金额</th>
          <th scope="col">期数</th>
          <th scope="col">首付款</th>
          <th scope="col">保证金</th>
          <th scope="col">费用</th>
          <th scope="col">平利</th>            
          <th scope="col">还款方式</th>
          <th scope="col">还款间隙</th>
          <th scope="col">XIRR</th>
          <th scope="col">连续复利IRR</th>
        </tr>
      </thead>
      <tbody>
      {% for tran in trans %}
        <tr>
          <th scope="row">{{ tran.id }}</th>
          <td>{{ tran.equip_amount }}</td>
          <td>{{ tran.rent_period }}</td>
          <td>{{ tran.downpayment }}</td>
          <td>{{ tran.deposit }}</td>
          <td>{{ tran.fee }}</td>
          <td>{{ tran.flat_rate*100 }}%</td>            
          <td>{{ tran.payment_type }}</td>
          <td>{{ tran.payment_period }}</td>
          <td>{{ tran.irr_nor }}%/年</td>
          <td>{{ tran.irr_exp }}%/年</td>          
          <td><a href="{{ url_for('irr_calculators.irr_cashflows', trade_id=tran.id) }}" ><button type="button" class="btn btn-primary btn-sm">测算</button></a></td>
          <td><a href="{{ url_for('irr_calculators.trade_update', trade_id=tran.id) }}" ><button type="button" class="btn btn-primary btn-sm">更新</button></a></td>
          <td><a href="{{ url_for('irr_calculators.trade_delete', trade_id=tran.id) }}" ><button type="button" class="btn btn-danger btn-sm">删除</button></a></td>
          
        </tr>

      {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock %}